version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    container_name: fastapi-proxy
    ports:
      - 80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi

  fastapi:
    image: aohus/apt-alarm:v0.1
    container_name: apt-alarm
    ports:
      - 8000:8000
    environment:
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_URL=${MONGO_DB_URL}
      - MONGO_MIN_CONNECTIONS=${MONGO_MIN_CONNECTIONS}
      - MONGO_MAX_CONNECTIONS=${MONGO_MAX_CONNECTIONS}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
      - SLACK_TOKEN=${SLACK_TOKEN}
    restart: always
