version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=apt-alarm
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: apt-alarm
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb://mongodb:27017
      - MONGO_DB=apt-alarm
    restart: always

volumes:
  mongodb_data:
