version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_DB_NAME=apt-alarm
      - MONGO_DB_ROOT_USERNAME=admin
      - MONGO_DB_ROOT_PASSWORD=password
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: apt-alarm
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_NAME=apt-alarm
      - MONGO_DB_URL=mongodb://mongodb:27017
      - SLACK_CHANNEL={YOUR_CHANNEL}
      - SLACK_TOKEN={YOUR_TOKEN}
    restart: always

volumes:
  mongodb_data:
